FROM node:8.0.0-alpine

RUN apk add --update nginx
RUN rm -rf /var/cache/apk/*
RUN mkdir -p /run/nginx
WORKDIR /usr/src/messenger
ADD . /usr/src/messenger
ADD ./default.conf /etc/nginx/conf.d/default.conf
RUN npm i
RUN npm run build
VOLUME /usr/src/messenger
ENTRYPOINT ["/usr/sbin/nginx", "-g", "daemon off;"]
