version: '3'
services:

  messenger:
    image: registry.jincor.com/frontend/messenger:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - ./:/usr/src/messenger
    command: npm run build

  nginx:
     image: registry.jincor.com/frontend/nginx:latest
     volumes:
       - ./dist:/var/apps/msg
     ports:
        - 80:80
        - 443:443